// <auto-generated />
namespace ASP_Vidly_Udemy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixPropertyNameFromIntToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixPropertyNameFromIntToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201907040941179_fixPropertyNameFromIntToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
